---
title: "Project title"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

## INTRODUCTION

describe your topic (citing sources)

provide a concise, clear statement of your research question and hypotheses

consider any potential ethical issues that you believe should be addressed (if any) regarding how your data were collected

identify the source of the data

when and how it was collected

the cases

a general description of relevant variables

For this research topic, we would have to take a look at which ages, heights, and weights have received medals. I would hypothesize that for each separate sport, there is a different normal distribution for ages, heights, and weights that have medal success rates, with an ideal age, height, and weight for each individual sport.

How do factors like age, height, and weight correlate with medal success rate across gymnastics and swimming?

## METHODOLOGY

visualizations and summary statistics relevant to your research question

justify the choice of statistical method(s) used to answer your research question

## RESULTS

1.   select only the parts of the data set we need (filter by sports)
2.  mutate to get the medal values numeric
3.  visualize the height and weight and whether or not they received a medal
4.  then separate by gender and see if it changes

showcase how you arrived at answers to your research question using the techniques we have learned in class

provide only the main results from your analysis

demonstrate that you are proficient at asking meaningful questions and answering them using data

that you are skilled in interpreting and presenting results

and that you can accomplish these tasks using R
